//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestFilter.Configurations
{
    
    
    /// <summary>
    /// The RequestFilterSection Configuration Section.
    /// </summary>
    public partial class RequestFilterSection : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the RequestFilterSection Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string RequestFilterSectionSectionName = "requestFilterSection";
        
        /// <summary>
        /// Gets the RequestFilterSection instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public static global::RequestFilter.Configurations.RequestFilterSection Instance
        {
            get
            {
                return ((global::RequestFilter.Configurations.RequestFilterSection)(global::System.Configuration.ConfigurationManager.GetSection(global::RequestFilter.Configurations.RequestFilterSection.RequestFilterSectionSectionName)));
            }
        }
        #endregion
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::RequestFilter.Configurations.RequestFilterSection.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::RequestFilter.Configurations.RequestFilterSection.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Filters Property
        /// <summary>
        /// The XML name of the <see cref="Filters"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string FiltersPropertyName = "filters";
        
        /// <summary>
        /// Gets or sets the Filters.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Filters.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::RequestFilter.Configurations.RequestFilterSection.FiltersPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public global::RequestFilter.Configurations.Filters Filters
        {
            get
            {
                return ((global::RequestFilter.Configurations.Filters)(base[global::RequestFilter.Configurations.RequestFilterSection.FiltersPropertyName]));
            }
            set
            {
                base[global::RequestFilter.Configurations.RequestFilterSection.FiltersPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace RequestFilter.Configurations
{
    
    
    /// <summary>
    /// A collection of Filter instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::RequestFilter.Configurations.Filter), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::RequestFilter.Configurations.Filters.FilterPropertyName)]
    public partial class Filters : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::RequestFilter.Configurations.Filter"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string FilterPropertyName = "filter";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override string ElementName
        {
            get
            {
                return global::RequestFilter.Configurations.Filters.FilterPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::RequestFilter.Configurations.Filters.FilterPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::RequestFilter.Configurations.Filter)(element)).Key;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::RequestFilter.Configurations.Filter"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::RequestFilter.Configurations.Filter"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::RequestFilter.Configurations.Filter();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::RequestFilter.Configurations.Filter"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::RequestFilter.Configurations.Filter"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::RequestFilter.Configurations.Filter this[int index]
        {
            get
            {
                return ((global::RequestFilter.Configurations.Filter)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::RequestFilter.Configurations.Filter"/> with the specified key.
        /// </summary>
        /// <param name="key">The key of the <see cref="global::RequestFilter.Configurations.Filter"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::RequestFilter.Configurations.Filter this[object key]
        {
            get
            {
                return ((global::RequestFilter.Configurations.Filter)(base.BaseGet(key)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::RequestFilter.Configurations.Filter"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="filter">The <see cref="global::RequestFilter.Configurations.Filter"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public void Add(global::RequestFilter.Configurations.Filter filter)
        {
            base.BaseAdd(filter);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::RequestFilter.Configurations.Filter"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="filter">The <see cref="global::RequestFilter.Configurations.Filter"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public void Remove(global::RequestFilter.Configurations.Filter filter)
        {
            base.BaseRemove(this.GetElementKey(filter));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::RequestFilter.Configurations.Filter"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::RequestFilter.Configurations.Filter"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::RequestFilter.Configurations.Filter GetItemAt(int index)
        {
            return ((global::RequestFilter.Configurations.Filter)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::RequestFilter.Configurations.Filter"/> with the specified key.
        /// </summary>
        /// <param name="key">The key of the <see cref="global::RequestFilter.Configurations.Filter"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::RequestFilter.Configurations.Filter GetItemByKey(string key)
        {
            return ((global::RequestFilter.Configurations.Filter)(base.BaseGet(((object)(key)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace RequestFilter.Configurations
{
    
    
    /// <summary>
    /// The Filter Configuration Element.
    /// </summary>
    public partial class Filter : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Type Property
        /// <summary>
        /// The XML name of the <see cref="Type"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string TypePropertyName = "type";
        
        /// <summary>
        /// Gets or sets the Type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Type.")]
        [global::System.ComponentModel.TypeConverter(typeof(global::System.Configuration.TypeNameConverter))]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::RequestFilter.Configurations.Filter.TypePropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public global::System.Type Type
        {
            get
            {
                return ((global::System.Type)(base[global::RequestFilter.Configurations.Filter.TypePropertyName]));
            }
            set
            {
                base[global::RequestFilter.Configurations.Filter.TypePropertyName] = value;
            }
        }
        #endregion
        
        #region Index Property
        /// <summary>
        /// The XML name of the <see cref="Index"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string IndexPropertyName = "index";
        
        /// <summary>
        /// Gets or sets the Index.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Index.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::RequestFilter.Configurations.Filter.IndexPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public int Index
        {
            get
            {
                return ((int)(base[global::RequestFilter.Configurations.Filter.IndexPropertyName]));
            }
            set
            {
                base[global::RequestFilter.Configurations.Filter.IndexPropertyName] = value;
            }
        }
        #endregion
        
        #region Key Property
        /// <summary>
        /// The XML name of the <see cref="Key"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string KeyPropertyName = "key";
        
        /// <summary>
        /// Gets or sets the Key.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Key.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::RequestFilter.Configurations.Filter.KeyPropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public string Key
        {
            get
            {
                return ((string)(base[global::RequestFilter.Configurations.Filter.KeyPropertyName]));
            }
            set
            {
                base[global::RequestFilter.Configurations.Filter.KeyPropertyName] = value;
            }
        }
        #endregion
        
        #region Params Property
        /// <summary>
        /// The XML name of the <see cref="Params"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string ParamsPropertyName = "params";
        
        /// <summary>
        /// Gets or sets the Params.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Params.")]
        [global::System.ComponentModel.TypeConverter(typeof(global::System.Configuration.CommaDelimitedStringCollectionConverter))]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::RequestFilter.Configurations.Filter.ParamsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public global::System.Configuration.CommaDelimitedStringCollection Params
        {
            get
            {
                return ((global::System.Configuration.CommaDelimitedStringCollection)(base[global::RequestFilter.Configurations.Filter.ParamsPropertyName]));
            }
            set
            {
                base[global::RequestFilter.Configurations.Filter.ParamsPropertyName] = value;
            }
        }
        #endregion
    }
}
